# NOTE: this file is disabled

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "Asia/Tokyo"
    target-branch: "main"
