apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    svc2pod: wordpress
  ports:
    - port: 80
      targetPort: http
  sessionAffinity: ClientIP # 同一セッションを常に同じPodに流す
  type: LoadBalancer
