name: renovate-config-validator

on: workflow_call

jobs:
  renovate-config-validator:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: true # for private repositories
          submodules: true

      - name: validate renovate.json
        run: npx --package=renovate@latest -c renovate-config-validator
