# FIXME: not working when fetching repository
name: update-submodules

on:
  workflow_call:
    secrets:
      ACTIONS_GITHUB_TOKEN:
        required: true
        description: "GitHub token for checkout and PR creation"

jobs:
  update-submodules:
    runs-on: ubuntu-24.04
    permissions: {}
    timeout-minutes: 20
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout files
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          submodules: true
          persist-credentials: false

      - name: Update submodules
        run: git submodule update --remote --recursive

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
        with:
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          commit-message: "contents: update submodule"
          title: "contents: update submodule"
